site_name: Nand - RPG
site_url: https://hoendel.github.io/HOE_Sandbox/
site_description: Offizielles Regel- und Setting-Kompendium zum Nand-RPG
repo_url: https://github.com/Hoendel/HOE_Sandbox
repo_name: HOE_Sandbox

docs_dir: docs_sample
use_directory_urls: true

theme:
  name: material
  language: de
  custom_dir: overrides
  features:
    - navigation.tracking
    - navigation.prune
    - navigation.indexes
    - navigation.footer
  palette:
    - scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-night
        name: Dunkles Design aktivieren
    - scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/weather-sunny
        name: Helles Design aktivieren

extra:
  announcement: "NAND – das Rollenspiel · Offizielles Regel- & Setting-Kompendium"

extra_css:
  - assets/css/banner.css
  - assets/css/aa.css
  - assets/css/typography.css
  - assets/css/sidebar-primary.css
  - assets/css/sidebar-secondary.css
  - assets/css/tokens.css

extra_javascript:
  - assets/js/aa.js
  #- assets/js/sidebar-auto.js

plugins:
  - search:
      lang: de

copyright: "© 2025 Nand – RPG"

nav:
  - "🏠 Startseite":
      - "Willkommen": index.md
      - "Nie wieder !": startseite/nie_wieder.md
      - "Sound": startseite/sound.md
  - "🧑‍🚀 Charakter & Regeln":
      - "Charaktererstellung": rules/charaktererstellung.md
      - "Charakterbögen": rules/charakterboegen.md
      - "Regeln": rules/regeln.md
  - "📋 Spielleiterhilfen":
      - "Vorbereitung": spielleiterhilfen/spielleiterhilfen.md
      - "Materialsystem": spielleiterhilfen/materiallisten.md
  - "🪖 Kadettschaft":
      - "Allgemeine Infos": kadettschaft/allgemein.md
      - "Rangabzeichen": kadettschaft/rangabzeichen.md
  - "🌍 Weltbeschreibung":
      - "Mars": welt/mars.md
      - "Bromsal": welt/bromsal.md
      - "Zeitlinien": welt/timeline.md
      - "Sonnensystem": welt/sonnensystem.md
      - "Quantenraum": welt/quantenraum.md
      - "Karten": welt/karten.md
  - "🛠️ Ausrüstung":
      - "Übersicht": ausruestung/index.md
      - "Geraffel": ausruestung/geraffel.md
      - "Anzüge": ausruestung/anzuege.md
      - "Helme": ausruestung/helme.md
      - "Leichtatmer & Handschuhe": ausruestung/leichtatmer-und-handschuhe.md
  - "⚙️ Technik":
      - "Kommunikation & Medizin":
          - "Kommunikation": technik/kommunikation.md
          - "Medizin": technik/medizin.md
      - "Fahrzeuge & Waffen":
          - "Vehikel": technik/vehikel.md
          - "Waffen":
              - "Granaten": technik/waffen/granaten.md
  - "🧑‍🌾 Kultur & Alltag":
      - "Marser": kultur/marser.md
      - "Hobbys": kultur/hobbys.md
      - "Kommunikation": kultur/kommunikation.md
  - "👽 Kräfte & Völker":
      - "Völkerübersicht": kraefte/voelker.md
      - "KI": kraefte/ki.md
      - "AKI": kraefte/aki.md
      - "Brom": kraefte/brom.md
      - "Gott": kraefte/gott.md
      - "Raummolche": kraefte/raummolche.md
  - "🎲 Abenteuer":
      - "Hauptkampagne":
          - "Wehrerziehungslager": abenteuer/01-wehrerziehungslager.md
          - "Der erste Auftrag": abenteuer/02-erster-auftrag.md
          - "Stimme aus der Stille": abenteuer/03-stimme-aus-der-stille.md
      - "Solo-RPG":
          - "Mini-RPG": abenteuer/99-mini-rpg.md
      - "NPC-Datenbank":
          - "Wehrerziehungslager": npc/wehrerziehungslager.md
  - "⚖️ Impressum & Datenschutz": impressum.md

